### ISSUE TITLE
Danfoss Ally error After updating to Core: 2024.5.0

### ISSUE THREAD

**Issue by Nislund** [MTrab/danfoss_ally#112]
### Describe the issue

After updating to Core: 2024.5.0 Danfoss Ally I get this error:

climate/set_preset_mode. Detected that custom integration 'danfoss_ally' calls async_write_ha_state from a thread at custom_components/danfoss_ally/climate.py, line 234: self.async_write_ha_state(). Please report it to the author of the 'danfoss_ally' custom integration.

### What version of Home Assistant Core has the issue?

core-2024.5.0

### What type of installation are you running?

Home Assistant OS

**Comment by oveand** [comment]
Seeing similar issues. A bit more of debug log:

```
Tempstyring stue: Error executing script. Unexpected error for repeat at pos 2: Detected that custom integration 'danfoss_ally' calls async_write_ha_state from a thread at custom_components/danfoss_ally/climate.py, line 295: self.async_write_ha_state(). Please report it to the author of the 'danfoss_ally' custom integration.

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 501, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 736, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 699, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 913, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 713, in async_set_temperature
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/danfoss_ally/climate.py", line 295, in set_temperature
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1008, in async_write_ha_state
    self.hass.verify_event_loop_thread("async_write_ha_state")
  File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
    frame.report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
    _report_integration(what, integration_frame, level, error_if_integration)
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
    raise RuntimeError(
RuntimeError: Detected that custom integration 'danfoss_ally' calls async_write_ha_state from a thread at custom_components/danfoss_ally/climate.py, line 295: self.async_write_ha_state(). Please report it to the author of the 'danfoss_ally' custom integration.
```

**Comment by oveand** [comment]
Digging a bit into this, seems like it’s just updating the async_write_ha_state() to schedule_update_ha_state() - that fixed it for me. Updated the following files:

```
custom_components/danfoss_ally $ grep -r async_write_ha_state .
./switch.py:        self.async_write_ha_state()
./switch.py:        self.async_write_ha_state()
./sensor.py:        self.async_write_ha_state()
./binary_sensor.py:        self.async_write_ha_state()
./climate.py:        self.async_write_ha_state()
./climate.py:            self.async_write_ha_state()
./climate.py:            self.async_write_ha_state()
./climate.py:        self.async_write_ha_state()
./climate.py:        self.async_write_ha_state()
./select.py:        self.async_write_ha_state()
./select.py:        self.async_write_ha_state()
```
